GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62eff70c38359fcaa51105ca

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Fidya",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/62eff70c38359fcaa51105ca

###

PATCH http://localhost:3000/subscribers/62eff37f275f3a21aeff0089
Content-Type: application/json

{
    "name": "Rezi"
}